/*
    Document   : Product.java
    Package	   : WebServices.net.resource.ws;
    Created on : July 25, 2022
    Author     : Cloyd Van S. Secuya
    Description:
    	This is the Product class describing the attributes for product code, product name, brand type, and its price. 
    	The products of the application will be stored in the database and pulled by a request from the Client.
		
		Additionally, here are the members of this class:
			product_code: String 
			name: String 
			brand: String
			price: Integer
			
		The product_code will be generated by a key generation algorithm which is an alphanumeric sequence.
*/

// PACKAGE
package net.resources.ws;


public class Product {
	
	private String product_code;
	private String product_name;
	private double price;
	
	// Key Generation Algorithm
	private KeyGeneration keygen = new KeyGeneration(); 
	
	public Product(String product_code, String product_name, double price) {
		/**
		 * @param String product_name : pass the name of the product
		 * @param String product_brand : pass the brand attribute of the product 
		 * @param int item_code : assign an item code to fetch for restful
		 * @param int price : pass the price of Integer type
		 * @note product_code is automatically generated
		 */
		this.product_code = product_code; 
		this.product_name = product_name; 
		this.price = price;
	}
	
	public Product(String product_name, double price) {
		/**
		 * @note This only instantiates the name and price
		 * @note then the rest is automatically generated
		 * @param product_name pass the name instnace
		 * @param price pass the price here
		 */
		// Upon instantiation set up the ID
		keygen.setRGN();
		// Assign the generated alphanumeric sequence 
		this.product_code = keygen.genKEY(); 
		this.product_name = product_name;
		this.price = price; 
	}
	
	public Product(String product_code) {
		/**
		 * @param Pass in the specified alphanumeric code
		 */
		this.product_code = product_code;
	}
	
	
	public Product() {
		/**
		 * @default Using the default constructor. Assign an automatic alphanumeric Product_ID
		 */
		// Upon instantiation set up the ID
		keygen.setRGN();
		// Assign the generated alphanumeric sequence 
		this.product_code = keygen.genKEY(); 
	}
	
	
	/**
	 * Getters and Setters for debugging and manually assigning attributes
	 */
	public void setProduct_code(String code) {
		this.product_code = code; 
	}
	
	public String getProduct_code( ) {
		return product_code;
	}
	
	public void setProduct_name(String name) {
		this.product_name = name;  
	}
	
	public String getProduct_name() {
		return product_name; 
	}
	
	public void setProduct_price(double price) {
		this.price = price;
	}
	
	public double getProduct_price() {
		return price;
	}

}
